### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by mcdurdin** [keymanapp/status.keyman.com#3]
- [x] Support `PENDING` state for pull requests
- [x] List crash report counts for each platform
- [x] List PRs that have no platform tag
- [x] PRs that are tagged with a Future milestone should be greyed down
- [x] PRs that are in draft should be greyed down.
- [x] List other repos (or at least PRs against them)?
- [x] List issue counts for othe repos (by milestone?)
- [x] Genericize the milestone array -- so we can break down by upcoming milestones while in beta
- [x] List issues without a milestone
- [ ] Capture metrics from Chris's spreadsheet
- [x] Show review status on PRs with an icon
- [x] Show PR owners with tiny avatar
- [x] Make the platform title a link to open PRs for the platform.
- [x] Move unlabeled PRs/issues to status bar (next to New Issues flag)
- [x] Figure out rate limiting
- [x] Show pending build on tier columns in yellow
- [x] If a PR has a successful build on an earlier commit, then a later commit (e.g. history.md) might not trigger a rebuild and we won't see the status of the build visible as a colour on the PR
- [x] Stable builds are not showing status
- [x] "Other" issues link should go to issues with "no:milestone" rather than "milestone:other" (special case!)
- [x] Grey out "Beta" column (or remove) while no 'beta' branch exists
- [x] Hover over contributions table drops the hover when reload occurs (because mouse is temporarily over background so we lose hover state in the tree...)
- [x] Click on contribution avatar should lock the contribution table open -- mitigates above issue
- [x] 'work-in-progress' label should be treated same as Draft

**Comment by mcdurdin** [comment]
I think we've diverged from Chris's spreadsheet for now! All else done.
